apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-dump-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "data/google.mobility.sql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-dump-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

