apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    app: db
spec:
  ports:
  - port: 3306
    name: db
  selector:
    app: db
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-mobility
  labels:
    app: db
spec:
  serviceName: "db"
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      generateName: db-mobility
      labels:
        app: db
    spec:
      containers:
      - name: db-mobility
        image: mysql:8.0
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 3306
          name: db
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-root-pass
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: db-name
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: sql-schema-data
          mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: sql-schema-data
          persistentVolumeClaim:
            claimName: sql-dump-pv-claim
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi

